definitions:
  models.Abrigo:
    properties:
      cidade:
        type: string
      foto:
        type: string
      nome:
        type: string
      sobre:
        type: string
      telefone:
        type: string
      uf:
        type: string
    type: object
  models.Tutor:
    properties:
      cidade:
        type: string
      foto:
        type: string
      nome:
        type: string
      sobre:
        type: string
      telefone:
        type: string
    type: object
host: localhost:8080/
info:
  contact:
    email: support@swagger.io
    name: API AdoPet
    url: https://www.google.com/
  description: API para o aplicativo AdoPet
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: AdoPet
  version: 0.0.1
paths:
  /abrigo:
    get:
      description: Rota para consultar todos os Abrigos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Abrigo'
      summary: Consulta todos os Abrigos
      tags:
      - Abrigo
    post:
      consumes:
      - application/json
      description: Criar um novo perfil de Abrigo
      parameters:
      - description: Informe os dados do Abrigo
        in: body
        name: Abrigo
        required: true
        schema:
          $ref: '#/definitions/models.Abrigo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Abrigo'
      summary: Criar um novo perfil de Abrigo
      tags:
      - Abrigo
  /abrigo/{id}:
    get:
      description: Recupera um abrigo do banco de dados com base no ID
      parameters:
      - description: ID do abrigo para consulta
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Abrigo'
        "404":
          description: Not Found
          schema: {}
      summary: Recupera um abrigo por ID
      tags:
      - Abrigo
    patch:
      description: Alterar um abrigo no banco de dados
      operationId: alterAbrigo
      parameters:
      - description: ID do abrigo a ser alterado
        in: path
        name: id
        required: true
        type: integer
      - description: Dados do abrigo a serem atualizado
        in: body
        name: abrigo
        required: true
        schema:
          $ref: '#/definitions/models.Abrigo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Abrigo'
        "400":
          description: Bad Request
          schema: {}
      summary: Alterar um abrigo existente.
      tags:
      - Abrigo
  /home:
    get:
      description: Rota para testar a API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Rota para testar a API
      tags:
      - home
  /tutor:
    get:
      description: Rota para consultar todos os Tutores
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tutor'
      summary: Consulta todos os Tutores
      tags:
      - Tutor
    post:
      consumes:
      - application/json
      description: Criar um novo Tutor
      parameters:
      - description: Informe os dados do Tutor
        in: body
        name: Tutor
        required: true
        schema:
          $ref: '#/definitions/models.Tutor'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tutor'
      summary: Criar um novo Tutor
      tags:
      - Tutor
swagger: "2.0"
